### ISSUE TITLE
Better Implementation

### ISSUE THREAD

**Issue by thefloatman** [phitonthel/MCNPX-Generator-Reader#1]
I think it's better to save the CAMOP input into a file and then use pythonic way to read and write or replace specific line for better code

```python
def replace_specific_line(line_number, read_file_name, line_content, write_file_name, save_path=DIRECTORY):
    read_file = open(read_file_name, "r")
    list_of_lines = read_file.readlines()
    list_of_lines[line_number - 1] = f"{line_content}\n"
    read_file.close()

    write_file_name = os.path.join(save_path, write_file_name)

    write_file = open(write_file_name, "w+") #will create if there is no file
    write_file.writelines(list_of_lines)
    write_file.close()
```

and also i see there is quite long output in the jupyter cell, for the example the following code

```python
files.upload
```

maybe you can see something like this for better readability

https://stackoverflow.com/questions/37154329/jupyter-notebook-command-for-hide-the-output-of-a-cell/38311906

**Comment by phitonthel** [comment]
Wow, thanks! Really appreciate the feedback!
